name: 'Check in Bot'
description: 'A GitHub Action to check for inactive issues and prompt for check-ins'
inputs:
  repo-token:
    description: 'GitHub token with repo scope'
    required: true
  days-inactive:
    description: 'Number of days of inactivity before posting'
    required: true
    default: '14'
 
  bot-username:
    description: 'Username of the bot'
    required: true
  ignore-label:
    description: 'Label to ignore issues with'
    required: false
    default: 'ignore-checkin'
  check-in-message:
    description: 'The check in message for issues and PRs (supports markdown)'
    required: true
    default: |
      Hello to the maintainers and watchers!

      There have been no updates here for the last two weeks. There might be need for a check in :)

      Thanks and hope all are well! ❤️
runs:
  using: 'node20'
  main: 'dist/index.js'