name: 'Check in Bot'
description: 'A GitHub Action to check for inactive issues and prompt for check-ins'
inputs:
  repo-token:
    description: 'GitHub token with repo scope'
    required: true
  days-inactive:
    description: 'Number of days of inactivity before posting'
    required: true
    default: '14'
  comment-message:
    description: 'Message to post on inactive issues'
    required: true
    default: 'This issue has been inactive for {{ days-inactive }} days. Please check in.'
  bot-username:
    description: 'Username of the bot'
    required: true
  ignore-label:
    description: 'Label to ignore issues with'
    required: false
    default: 'ignore-checkin'
runs:
  using: 'node16'
  main: 'dist/index.js'